### ISSUE TITLE
Possibility to copy code for both light and dark theme at the same time

### ISSUE THREAD

**Issue by cyrilf** [Microwawe/mamba-ui#107]
Currently on the website I can choose a dark or light theme and copy the associated code.
It would be awesome to have the possibility to copy/paste a version of the code handling both cases.

For instance, instead of having:

`bg-gray-800 text-gray-100` for the light version and `dark:bg-gray-800 dark:text-gray-100` for the dark version, having a mix like so: `bg-gray-800 text-gray-100 dark:bg-gray-800 dark:text-gray-100`

Maybe there is an option, but I haven't found it.

Thanks!

**Comment by Microwawe** [comment]
Right now there isn't an option to do that but it's a good suggestion, I'll see if that is easily doable

**Comment by Microwawe** [comment]
Took a bit more refactoring than I thought but that should work now
![image](https://github.com/Microwawe/mamba-ui/assets/26537592/0fa57336-ccbc-4b2e-9d3e-2bbc2f491901)

**Comment by cyrilf** [comment]
Awesome! Thanks a lot for that! :tada:
