### ISSUE TITLE
Inconsistent Attribute Naming in MambaUi Form Components Hindering React Integration

### ISSUE THREAD

**Issue by Anawrulkabir** [Microwawe/mamba-ui#111]
Dear MambaUi Team,

As an active developer leveraging MambaUi components within React projects, I'd like to express appreciation for the value your library brings to front-end development.

However, during integration efforts, I noticed discrepancies in attribute naming within the JSX files of MambaUi form components. Specifically:

1. **`<form>` Component:** The `novalidate` attribute is currently represented as `novalidate=""`, deviating from React's expected `noValidate=""` casing convention.
   
2. **`<label>` Component for Password Field:** The `for` attribute is currently written as `for="password"`, whereas React expects `htmlFor="password"` for proper functionality.

These inconsistencies may cause confusion among developers familiar with React's conventions, potentially leading to debugging challenges and decreased productivity.

Addressing these minor yet crucial attribute naming inconsistencies would significantly enhance the compatibility and usability of MambaUi components within React projects. It would streamline the integration process and ensure a seamless development experience for users of your library.

I kindly request the MambaUi team to review and rectify these attribute namings in the provided form components, aligning them with React's conventions.

Thank you for your attention to this matter. Should you require further clarification or assistance, please feel free to reach out.

**Comment by Microwawe** [comment]
Hi,

Thanks for raising the issue and letting us know. I've fixed these two but I'm not that familiar with React's syntax so if you find more of these problems in the future please let us know and we'll fix them asap.
