### ISSUE TITLE
Bug in a JSX Code Section 

### ISSUE THREAD

**Issue by kumard3** [Microwawe/mamba-ui#61]
![Screenshot 2022-05-10 at 6 42 03 PM](https://user-images.githubusercontent.com/62591080/167636448-c773623e-d0d6-4fc3-a329-476eb39a79bf.png) 
Ending Quotes are missing 

Any way I can  contribute ?

**Comment by Microwawe** [comment]
Hi!

Yea you can try to debug and/or fix that if you want. If that extra comment tag is only in the jsx part then the issue most likely is in `src/app/core/services/formatter.service.ts`

**Comment by Microwawe** [comment]
Hi, I think I found the problem and it should be fixed now. 

Thanks for reporting the bug! And let me know if there are any other issues with Mamba UI and I'll try to fix them asap.
