### ISSUE TITLE
All links inside components redirect to the home page.

### ISSUE THREAD

**Issue by Sepulven** [Microwawe/mamba-ui#93]
Unfortunately, when searching for components and interacting with them we might get redirect to the home page thus halting our search.
The reason why it happens is the `href="#" ` attr in the `<a>` tag, if we set it to` href=""` it won't happen again.
Different components has the tag and as user we got this unexpected behavior when clicking over them therefore ruining the user experience.

**Comment by Microwawe** [comment]
Hi, 
Thanks for letting me know, I'll take a look at this later this week.
