### ISSUE TITLE
Buttons on carousel component don't work

### ISSUE THREAD

**Issue by Sepulven** [Microwawe/mamba-ui#94]
Buttons on carousel are not working, when clicked nothing happens.

[Screencast from 02-11-2023 18:29:46.webm](https://github.com/Microwawe/mamba-ui/assets/67148192/04d08a07-ae47-443b-9064-ac67d5c91560)

https://mambaui.com/components/carousel

P.S.:  The buttons can't be seem.

**Comment by Microwawe** [comment]
Hi,
The buttons don't do anything because all of the components in Mamba UI are just html+css so you'll have to add the javascript logic yourself later if needed/wanted. 😄

I'll try to make them more visible by default
